name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust components
        run: rustup component add rustfmt clippy
      - name: Test aye
        run: make -C aye test
      - name: Test aye-view
        run: make -C aye-view test
